FROM node:lts-buster-slim AS development

WORKDIR /usr/src/app

COPY . /usr/src/app
COPY proxy-docker.config.json /usr/src/app/proxy.config.json

RUN npm install -g @angular/cli

RUN npm install

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]